c:\users\class2~1\appdata\local\temp\FingerTipStudy-ABS Force Study
c:\users\class2~1\appdata\local\temp\FingerTipStudy-PLA Force Study
C:\Users\Class2014\Desktop\FingerTipStudy-ABS Drop Study
C:\Users\Class2014\Desktop\FingerTipStudy-PLA Drop Study
C:\Users\Class2014\Desktop\FingerMidStudy-PLA Force Analysis
C:\Users\Class2014\Desktop\FingerMidStudy-PLA Force Analysis
C:\Users\Class2014\Desktop\FingerMidStudy-PLA Force Analysis
C:\Users\Class2014\Desktop\FingerMidStudy-ABS Force Analysis
C:\Users\Class2014\Desktop\FingerMidStudy-ABS Drop Test
C:\Users\Class2014\Desktop\FingerMidStudy-PLA Drop Test
C:\Users\Class2014\Desktop\fingerbase-Study 1
C:\Users\Class2014\Desktop\fingerbase-PLA Force Study
C:\Users\Class2014\Desktop\fingerbase-PLA Force Study
